version: '3'

services:
  contact-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - MONGODB_URI=${MONGODB_URI}
    restart: always
